# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Saagar's Content Journal
tagline:             'reflections of consumption'
description:         'Why are you here? Made by <a href="https://instagram.com/saagargrips" target="_blank">@saagargrips</a>.'
baseurl:             ''
gems:                

# About/contact
author:
  name:              Saagar Godithi
  url:               
  email:             saagar@godithi.com

# Custom vars
version:             1.0.0
